package: wildcard
version: '0.1.0-dev-2024-12-30'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/wildcard


requires:
    php:
        version: '>=8.3,<9'
    redaxo: ^5.18
    packages:
        yform: "^4"



page:
    title: translate:wildcard_title
    icon: rex-icon fa-language
    block: system
    prio: 75
    perm: wildcard[]
    subpages:
        entry:
            title: translate:wildcard_wildcard
            icon: rex-icon fa-gear
            perm: wildcard[]
        settings:
            title: translate:wildcard_settings
            icon: rex-icon fa-gear
            itemClass: pull-right
            perm: admin
        docs:
            title: translate:wildcard_docs
            subPath: README.md
            icon: rex-icon fa-info-circle
            itemClass: pull-right
            perm: wildcard[docs]

default_config:
    syncdatestamp: ''
    opentag: '{{'
    closetag: '}}'

installer_ignore:
- .git
- .gitignore
- .github
- .php-cs-fixer.dist.php
